name: whatsapp_bot_platform_interface
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.5
  zxing2: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


