name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.1

dependencies:
  whatsapp_bot_flutter:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
