name: whatsapp_bot_flutter_mobile
description: Whatsapp bot using webview and whatsapp web scraping
version: 1.0.0
homepage: https://github.com/rohitsangwan01/whatsapp_bot_flutter
repository: https://github.com/rohitsangwan01/whatsapp_bot_flutter
issue_tracker: https://github.com/rohitsangwan01/whatsapp_bot_flutter/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_inappwebview: ^5.7.2+3
  whatsapp_bot_platform_interface: ^0.0.2

dev_dependencies:
  lints: ^2.0.1
