name: whatsapp_bot_flutter_mobile
description: Whatsapp bot using webview and whatsapp web scraping
version: 2.0.4
homepage: https://github.com/rohitsangwan01/whatsapp_bot_flutter
repository: https://github.com/rohitsangwan01/whatsapp_bot_flutter
issue_tracker: https://github.com/rohitsangwan01/whatsapp_bot_flutter/issues

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  whatsapp_bot_platform_interface: ^1.0.4

dependency_overrides: 
  whatsapp_bot_platform_interface: 
    path: ../whatsapp_bot_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
